# Generated by Django 3.2.22 on 2023-10-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20231010_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='categoryIndex',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
